server:
  port: 0

logging:
  level:
    com.example.orderservice: DEBUG

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mariadb://localhost:3308/mydb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: test1234
  #    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://10.30.1.138:8761/eureka
